'use client';
import Link from 'next/link';
import { useEffect,useMemo,useRef,useState } from 'react';
import { API_ORIGIN,apiFetch } from '@/lib/api';
import { cargarEstadisticas,cargarPublicaciones,EstadisticasPublicas,PublicacionPublica,SeccionPublica } from '@/lib/publicaciones';

const meses=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
const diasSemana=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
export default function PaginaPublica(){
 const[items,setItems]=useState<PublicacionPublica[]>([]),[stats,setStats]=useState<EstadisticasPublicas|null>(null),[menu,setMenu]=useState(false),[filtro,setFiltro]=useState('TODAS'),[abierta,setAbierta]=useState<PublicacionPublica|null>(null),[anio,setAnio]=useState<number>(),[error,setError]=useState('');
 const[marca,setMarca]=useState<{nombreSistemaMenu:string|null;subtituloMenu:string|null;logoMenu:string|null}>({nombreSistemaMenu:null,subtituloMenu:null,logoMenu:null});
 useEffect(()=>{Promise.all([cargarPublicaciones(),cargarEstadisticas(),apiFetch('/seguridad/apariencia').then(async r=>r.ok?await r.json():{nombreSistemaMenu:null,subtituloMenu:null,logoMenu:null})]).then(([p,s,a])=>{setItems(p);setStats(s);setAnio(s.anio);setMarca(a as typeof marca)}).catch(e=>setError(e.message))},[]);
 const section=(s:SeccionPublica)=>items.filter(x=>x.seccion===s);const portada=section('PORTADA').find(x=>x.destacada)||section('PORTADA')[0];const novedades=items.filter(x=>['NOTICIA','SUCESO','EVENTO'].includes(x.seccion)&&(filtro==='TODAS'||x.seccion===filtro));
 async function cambiarAnio(v:number){setAnio(v);try{setStats(await cargarEstadisticas(v))}catch(e:any){setError(e.message)}}
 const nombre=marca.nombreSistemaMenu||'Cuerpo de Bomberos Voluntarios';
 return <div className="public-site"><header className="public-header"><a className="public-brand" href="#inicio">{marca.logoMenu?<img src={`${API_ORIGIN}${marca.logoMenu}`} alt="Logo institucional"/>:<span className="public-logo">CB</span>}<span><b>{nombre}</b><small>{marca.subtituloMenu||'Institución de servicio voluntario'}</small></span></a><button type="button" className="public-menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Abrir menú">☰</button><nav className={menu?'open':''} onClick={()=>setMenu(false)}><a href="#inicio">Inicio</a><a href="#historia">Nuestra historia</a><a href="#flota">Móviles</a><a href="#estadisticas">Estadísticas</a><a href="#logros">Logros</a><a href="#novedades">Novedades</a><a href="#contacto">Contacto</a></nav><Link className="public-login" href="/denuncias">Realizar denuncia</Link><Link className="public-login" href="/login">Iniciar sesión</Link></header>
 <main id="contenido-principal" tabIndex={-1}>{error&&<div className="public-alert" role="alert">{error}</div>}
 <section id="inicio" className={`public-hero${portada?'':' empty'}`} style={portada?.imagen?{backgroundImage:`linear-gradient(90deg,rgba(8,31,60,.95),rgba(8,31,60,.42)),url(${portada.imagen})`}:undefined}>{portada?<div className="public-hero-content"><span className="public-kicker">{portada.subtitulo||nombre}</span><h1>{portada.titulo}</h1><p>{portada.resumen}</p><div className="hero-actions"><a className="public-button" href={portada.enlace||'#historia'}>{portada.botonTexto||'Conocé nuestro trabajo'}</a><a className="public-button secondary" href="#estadisticas">Ver estadísticas</a></div></div>:<Empty title="Portada institucional" text="La portada se mostrará cuando sea publicada desde el módulo Publicaciones."/>}</section>
 <section className="public-summary">{section('RESUMEN').length?section('RESUMEN').map(x=><article key={x.id}><strong>{x.titulo}</strong><span>{x.resumen}</span></article>):<Empty title="Resumen institucional" text="No hay indicadores editoriales publicados."/>}</section>
 <ContentSection id="historia" kicker="Nuestra historia" title="Una vocación construida con el tiempo" items={section('HISTORIA')} empty="La reseña histórica todavía no fue publicada." onOpen={setAbierta} layout="timeline"/>
 <section id="flota" className="public-section soft"><SectionHead kicker="Nuestra flota" title="Móviles y capacidad de respuesta"/><div className="fleet-summary">{stats&&Object.entries(stats.flota).map(([k,v])=><div key={k}><strong>{v}</strong><span>{({total:'Total',operativos:'Operativos',mantenimiento:'En mantenimiento',fueraServicio:'Fuera de servicio'} as any)[k]}</span></div>)}</div>{section('FLOTA').length?<Cards items={section('FLOTA')} onOpen={setAbierta}/>:<Empty title="Información de móviles" text="No hay fichas públicas de móviles cargadas. El resumen utiliza datos operativos reales."/>}</section>
 <section id="estadisticas" className="public-section stats-section"><div className="section-heading-public"><SectionHead kicker="Transparencia" title="Estadísticas públicas"/><select aria-label="Seleccionar período" value={anio} onChange={e=>cambiarAnio(Number(e.target.value))}><option value={0}>Todos los años</option>{stats?.anios.map(x=><option key={x.anio}>{x.anio}</option>)}</select></div>{stats?<><div className="stats-grid">{[['Total histórico',stats.indicadores.totalHistorico],[anio===0?'Servicios del período':'Servicios del año',stats.indicadores.totalAnio],[anio===0?'Servicios en este mes histórico':'Servicios del mes',stats.indicadores.totalMes],['Personal activo',stats.indicadores.personalActivo],['Móviles disponibles',stats.indicadores.movilesDisponibles],['Último servicio',stats.indicadores.ultimoServicio?new Date(stats.indicadores.ultimoServicio).toLocaleString('es-PY'):'Sin registros'],['Tiempo desde el último servicio',tiempoTranscurrido(stats.indicadores.ultimoServicio)]].map(([l,v])=><div key={String(l)}><strong>{v}</strong><span>{l}</span></div>)}</div>
 <Chart title="Servicios por mes" subtitle={stats.anio===0?'Todos los años':String(stats.anio)} values={stats.porMes.map(x=>({label:meses[x.mes-1],total:x.total}))}/><div className="visual-grid"><Chart title="Evolución por año" values={stats.porAnio.map(x=>({label:String(x.anio),total:x.total}))}/><Chart title="Actividad por día" values={stats.porDiaSemana.map(x=>({label:diasSemana[x.dia].slice(0,3),total:x.total}))}/><Chart title="Distribución por tipo" values={stats.porTipo.map(x=>({label:x.nombre,total:x.total}))}/></div>{anio!==0&&<div className="comparison-panel"><b>Comparación anual</b><span>{stats.anio}: {stats.comparacion.actual} servicios</span><span>{stats.anio-1}: {stats.comparacion.anterior} servicios</span></div>}
 <h3 className="records-title">Récords y datos destacados</h3><div className="records-grid"><Record title="Día con más servicios" value={stats.records.diaMaximo?`${stats.records.diaMaximo.total} servicios · ${fecha(stats.records.diaMaximo.fecha)}${stats.records.diaMaximo.empate?' · empate':''}`:'Sin información suficiente'}/><Record title="Mayor período sin servicios" value={stats.records.periodoSinServicios?`${duracion(stats.records.periodoSinServicios.horas)} · ${fecha(stats.records.periodoSinServicios.desde)} a ${fecha(stats.records.periodoSinServicios.hasta)}`:'Sin información suficiente'}/><Record title="Día de mayor actividad" value={stats.records.diaSemanaMaximo?`${diasSemana[stats.records.diaSemanaMaximo.dia]} · ${stats.records.diaSemanaMaximo.total} servicios${stats.records.diaSemanaMaximo.empate?' · empate':''}`:'Sin información suficiente'}/><Record title="Día de menor actividad" value={stats.records.diaSemanaMinimo?`${diasSemana[stats.records.diaSemanaMinimo.dia]} · ${stats.records.diaSemanaMinimo.total} servicios${stats.records.diaSemanaMinimo.empate?' · empate':''}`:'Sin información suficiente'}/><Record title="Mes de mayor actividad" value={extremoPeriodo(stats.records.mesMaximo)}/><Record title="Mes de menor actividad" value={extremoPeriodo(stats.records.mesMinimo)}/><Record title="Año con mayor actividad" value={stats.records.anioMaximo?`${stats.records.anioMaximo.periodo} · ${stats.records.anioMaximo.total} servicios${stats.records.anioMaximo.empate?' · empate':''}`:'Sin información suficiente'}/><Record title="Tipo más frecuente" value={stats.records.tipoFrecuente?`${stats.records.tipoFrecuente.nombre} · ${stats.records.tipoFrecuente.total} servicios`:'Sin información suficiente'}/><Record title="Promedios" value={stats.records.promedioMensual!==null?`${stats.records.promedioMensual} por mes · ${stats.records.promedioDiario} por día activo`:'Sin información suficiente'}/></div><h3 className="records-title">Récords por tipo de servicio</h3><div className="category-records">{stats.records.porCategoria.map(x=><article key={x.nombre}><h4>{x.nombre[0]+x.nombre.slice(1).toLowerCase()}</h4><strong>{x.total}</strong><span>Total histórico · {x.porcentaje}% de los servicios</span><p>Mes con más actividad: {extremoPeriodo(x.mesMaximo)}</p><p>Día con más actividad: {x.diaMaximo?`${fecha(x.diaMaximo.fecha)} · ${x.diaMaximo.total}${x.diaMaximo.empate?' · empate':''}`:'Sin información suficiente'}</p></article>)}</div></>:<Empty title="Estadísticas" text="No fue posible consultar la información operativa."/>}</section>
 <ContentSection id="logros" kicker="Logros y reconocimientos" title="Orgullo institucional" items={section('LOGRO')} empty="Todavía no hay logros o reconocimientos publicados." onOpen={setAbierta}/>
 <section id="novedades" className="public-section soft"><div className="section-heading-public"><SectionHead kicker="Actualidad" title="Noticias, sucesos y eventos"/><div className="filters">{['TODAS','NOTICIA','SUCESO','EVENTO'].map(x=><button className={filtro===x?'active':''} onClick={()=>setFiltro(x)} key={x}>{x==='TODAS'?'Todas':x[0]+x.slice(1).toLowerCase()}</button>)}</div></div>{novedades.length?<Cards items={novedades} onOpen={setAbierta}/>:<Empty title="Sin publicaciones" text="No hay contenido visible en esta categoría."/>}</section>
 <ContentSection id="eventos" kicker="Próximos eventos" title="Agenda comunitaria" items={section('EVENTO').filter(x=>!x.fecha||new Date(x.fecha+'T23:59')>=new Date())} empty="Actualmente no hay eventos programados." onOpen={setAbierta}/>
 <ContentSection id="transparencia" kicker="Transparencia institucional" title="Información para la comunidad" items={section('TRANSPARENCIA')} empty="No hay informes o campañas públicas disponibles." onOpen={setAbierta}/>
 <section id="contacto" className="contact-section"><SectionHead kicker="Contacto y emergencias" title="Canales institucionales"/>{section('CONTACTO').length?<div className="contact-grid">{section('CONTACTO').map(x=><article key={x.id}><h3>{x.titulo}</h3><p>{x.contenido||x.resumen}</p>{x.enlace&&<a href={x.enlace}>{x.botonTexto||x.enlace}</a>}</article>)}</div>:<Empty title="Información de contacto" text="Los canales de contacto se mostrarán cuando sean publicados."/>}</section></main>
 <footer className="public-footer"><div className="public-brand"><span className="public-logo">CB</span><span><b>{nombre}</b><small>{section('FOOTER')[0]?.contenido||''}</small></span></div><div><a href="#historia">Historia</a><a href="#estadisticas">Estadísticas</a><a href="#contacto">Contacto</a><Link href="/login">Iniciar sesión</Link></div><p>© {new Date().getFullYear()} · Todos los derechos reservados</p></footer>{abierta&&<Modal item={abierta} close={()=>setAbierta(null)}/>}</div>
}
function SectionHead({kicker,title}:{kicker:string;title:string}){return <div><p className="public-kicker">{kicker}</p><h2>{title}</h2></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="public-empty"><h3>{title}</h3><p>{text}</p></div>}
function Record({title,value}:{title:string;value:string}){return <article><span>{title}</span><b>{value}</b></article>}
function Chart({title,subtitle,values}:{title:string;subtitle?:string;values:{label:string;total:number}[]}){const max=Math.max(0,...values.map(x=>x.total));return <div className="chart-panel"><div><b>{title}</b>{subtitle&&<span>{subtitle}</span>}</div>{values.length?<><div className="bars">{values.map((x,i)=><i key={`${x.label}-${i}`} style={{height:`${max?Math.max(3,x.total/max*100):3}%`}} title={`${x.label}: ${x.total}`} aria-label={`${x.label}: ${x.total}`}/>)}</div><div className="chart-labels">{values.map((x,i)=><span key={`${x.label}-${i}`}>{x.label}</span>)}</div></>:<p>Sin información suficiente.</p>}</div>}
function fecha(value:string){return new Date(value.length===10?`${value}T12:00`:value).toLocaleDateString('es-PY')}
function duracion(horas:number){const dias=Math.floor(horas/24),resto=horas%24;return dias?`${dias} días y ${resto} horas`:`${horas} horas`}
function tiempoTranscurrido(value:string|null){if(!value)return 'Sin registros';const horas=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/3600000));return duracion(horas)}
function extremoPeriodo(value:{periodo:string;total:number;empate:boolean}|null){if(!value)return 'Sin información suficiente';const [y,m]=value.periodo.split('-');return `${m?meses[Number(m)-1]+' de ':''}${y} · ${value.total} servicios${value.empate?' · empate':''}`}
function Cards({items,onOpen}:{items:PublicacionPublica[];onOpen:(x:PublicacionPublica)=>void}){return <div className="posts-grid">{items.map(x=><article className="post-card" key={x.id}>{x.imagen&&<div className="post-image" role="img" aria-label={x.imagenAlt||''} style={{backgroundImage:`url(${x.imagen})`}}/>}<div><span style={{color:x.color}}>{x.categoria||x.seccion}</span>{x.fecha&&<time>{new Date(x.fecha+'T12:00').toLocaleDateString('es-PY')}</time>}<h3>{x.titulo}</h3><p>{x.resumen}</p><button onClick={()=>onOpen(x)}>Leer más →</button></div></article>)}</div>}
function ContentSection({id,kicker,title,items,empty,onOpen,layout}:{id:string;kicker:string;title:string;items:PublicacionPublica[];empty:string;onOpen:(x:PublicacionPublica)=>void;layout?:string}){return <section id={id} className={`public-section ${layout||''}`}><SectionHead kicker={kicker} title={title}/>{items.length?<Cards items={items} onOpen={onOpen}/>:<Empty title={title} text={empty}/>}</section>}
function Modal({item,close}:{item:PublicacionPublica;close:()=>void}){const panel=useRef<HTMLElement>(null),returnFocus=useRef<HTMLElement|null>(null);useEffect(()=>{returnFocus.current=document.activeElement as HTMLElement;const root=panel.current;root?.focus();function key(e:KeyboardEvent){if(e.key==='Escape')close();if(e.key==='Tab'&&root){const nodes=[...root.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!nodes.length){e.preventDefault();return}const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);returnFocus.current?.focus()}},[close]);return <div className="public-modal" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><article ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="modal-title" style={{borderTopColor:item.color}}><button type="button" aria-label="Cerrar" onClick={close}>×</button><span style={{color:item.color}}>{item.categoria||item.seccion}</span><h2 id="modal-title">{item.titulo}</h2>{item.imagen&&<img src={item.imagen} alt={item.imagenAlt}/>}<p>{item.contenido}</p>{item.enlace&&<a className="public-button" href={item.enlace}>{item.botonTexto||'Más información'}</a>}</article></div>}
