'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {aplicarConfiguracion,cargarPublica,cargarRegistroPublico,ConfigDefinition,guardarPreferenciasDispositivo,preferenciasDispositivo} from '@/lib/configuracion';

export function ConfigBootstrap(){
 const[open,setOpen]=useState(false),[defs,setDefs]=useState<ConfigDefinition[]>([]),[values,setValues]=useState<Record<string,unknown>>({}),[message,setMessage]=useState('');
 const drawer=useRef<HTMLElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const local=preferenciasDispositivo();setValues(local);aplicarConfiguracion(local);Promise.all([cargarPublica(),cargarRegistroPublico()]).then(([pub,registry])=>{const globals=Object.fromEntries(Object.entries(pub.values||{}).map(([k,v]:any)=>[k,v.value]));const merged={...globals,...local};setDefs(registry.filter((x:ConfigDefinition)=>x.userOverride));setValues(merged);aplicarConfiguracion(merged)}).catch(()=>undefined)},[]);
 useEffect(()=>{if(!open)return;const root=drawer.current;root?.focus();function key(e:KeyboardEvent){if(e.key==='Escape')setOpen(false);if(e.key==='Tab'&&root){const nodes=[...root.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);trigger.current?.focus()}},[open]);
 const groups=useMemo(()=>Object.entries(defs.reduce((a:Record<string,ConfigDefinition[]>,d)=>{(a[d.categoria]??=[]).push(d);return a},{})),[defs]);
 function change(key:string,value:unknown){const next={...values,[key]:value};setValues(next);aplicarConfiguracion(next)}
 function save(){const allowed=Object.fromEntries(defs.map(d=>[d.key,values[d.key]??d.defaultValue]));guardarPreferenciasDispositivo(allowed);setMessage('Preferencias guardadas en este dispositivo.')}
 function reset(){localStorage.removeItem('sigbo_device_preferences_v1');location.reload()}
 return <><button ref={trigger} type="button" className="config-fab" onClick={()=>setOpen(true)} aria-label="Abrir preferencias" title="Preferencias">⚙</button>{open&&<div className="config-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside ref={drawer} tabIndex={-1} className="config-drawer" role="dialog" aria-modal="true" aria-labelledby="config-title"><header><div><span>Preferencias</span><h2 id="config-title">Personalizá tu experiencia</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></header><p className="config-note">Estas opciones son locales, no contienen información sensible y no modifican datos institucionales.</p>{groups.map(([name,list]:any)=><section key={name}><h3>{name}</h3>{list.map((d:ConfigDefinition)=><ConfigField key={d.key} def={d} value={values[d.key]??d.defaultValue} onChange={v=>change(d.key,v)}/>)}</section>)}{message&&<p className="config-success" role="status" aria-live="polite">{message}</p>}<footer><button type="button" className="service-secondary" onClick={reset}>Restablecer</button><button type="button" className="btn-primary" onClick={save}>Guardar preferencias</button></footer></aside></div>}</>
}
function ConfigField({def,value,onChange}:{def:ConfigDefinition;value:unknown;onChange:(v:unknown)=>void}){return <label className="config-field"><span><b>{def.nombre}</b><small>{def.descripcion}</small></span>{def.tipo==='booleano'?<input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>:def.tipo==='color'?<input type="color" value={String(value)} onChange={e=>onChange(e.target.value)}/>:def.control==='slider'?<span className="config-slider"><input type="range" min={def.min} max={def.max} value={Number(value)} onChange={e=>onChange(Number(e.target.value))}/><output>{String(value)}{def.unidad}</output></span>:def.allowed?<select value={String(value)} onChange={e=>{const original=def.allowed?.find(x=>String(x)===e.target.value);onChange(original)}}>{def.allowed.map(x=><option key={String(x)} value={String(x)}>{String(x)}</option>)}</select>:<input value={String(value??'')} onChange={e=>onChange(e.target.value)}/>}</label>}
