<<<<<<< Updated upstream
import{BadRequestException,NotFoundException}from'@nestjs/common';import{PublicacionPublica,PublicacionesService}from'./publicaciones.service';
const base=(o:Partial<PublicacionPublica>={}):PublicacionPublica=>({id:'00000000-0000-0000-0000-000000000001',seccion:'NOTICIA',titulo:'Comunicado',subtitulo:'',resumen:'',contenido:'',fecha:'',fechaFin:'',hora:'',ubicacion:'',categoria:'',etiquetas:[],imagen:'',imagenAlt:'',color:'#2563eb',botonTexto:'',enlace:'',visible:true,destacada:false,orden:1,estado:'PUBLICADA',publicarEn:'',caducarEn:'',...o});
function setup(){const repo={find:jest.fn(),findOne:jest.fn(),exist:jest.fn(),save:jest.fn(),create:jest.fn(x=>x),delete:jest.fn()};return{service:new PublicacionesService({}as never,{}as never,{}as never,{}as never,repo as never),repo}}
describe('PublicacionesService',()=>{it('aplica visibilidad y programación',()=>{const{service}=setup(),fn=(x:PublicacionPublica)=>(service as unknown as{publicable:(x:PublicacionPublica,n:Date)=>boolean}).publicable(x,new Date('2026-08-12'));expect(fn(base())).toBe(true);expect(fn(base({visible:false}))).toBe(false);expect(fn(base({estado:'BORRADOR'}))).toBe(false);expect(fn(base({estado:'PROGRAMADA',publicarEn:'2026-08-13'}))).toBe(false)});it('rechaza contenido inseguro',()=>{const{service}=setup(),fn=(x:PublicacionPublica)=>(service as unknown as{validar:(x:PublicacionPublica)=>PublicacionPublica}).validar(x);expect(()=>fn(base({color:'red'}))).toThrow(BadRequestException);expect(()=>fn(base({enlace:'javascript:alert(1)'}))).toThrow(BadRequestException)});it('crea sin reemplazar otras publicaciones',async()=>{const{service,repo}=setup();repo.exist.mockResolvedValue(false);repo.findOne.mockResolvedValue(null);repo.save.mockImplementation(async x=>x);await service.crear(base());expect(repo.save).toHaveBeenCalledTimes(1);expect(repo.delete).not.toHaveBeenCalled()});it('protege ids inexistentes',async()=>{const{service,repo}=setup();repo.exist.mockResolvedValue(false);repo.delete.mockResolvedValue({affected:0});await expect(service.actualizar('x',base())).rejects.toBeInstanceOf(NotFoundException);await expect(service.eliminar('x')).rejects.toBeInstanceOf(NotFoundException)})});
=======
import { BadRequestException, NotFoundException } from '@nestjs/common';
import { PublicacionPublica, PublicacionesService } from './publicaciones.service';

const base=(overrides:Partial<PublicacionPublica>={}):PublicacionPublica=>({id:'pub-1',seccion:'NOTICIA',titulo:'Comunicado',subtitulo:'',resumen:'',contenido:'',fecha:'',fechaFin:'',hora:'',ubicacion:'',categoria:'',etiquetas:[],imagen:'',imagenAlt:'',color:'#2563eb',botonTexto:'',enlace:'',visible:true,destacada:false,orden:1,estado:'PUBLICADA',publicarEn:'',caducarEn:'',...overrides});
function crearServicio(){const repo={find:jest.fn(),findOne:jest.fn(),exist:jest.fn(),save:jest.fn(),create:jest.fn(x=>x),delete:jest.fn(),manager:{transaction:jest.fn()}};return{service:new PublicacionesService({} as never,{} as never,{} as never,{} as never,repo as never),repo}}

describe('PublicacionesService',()=>{
 it('filtra borradores, contenidos ocultos y programados',()=>{const{service}=crearServicio();const publica=(x:PublicacionPublica)=>(service as unknown as {publicable:(x:PublicacionPublica,n:Date)=>boolean}).publicable(x,new Date('2026-08-11T12:00:00Z'));expect(publica(base())).toBe(true);expect(publica(base({estado:'BORRADOR'}))).toBe(false);expect(publica(base({visible:false}))).toBe(false);expect(publica(base({estado:'PROGRAMADA',publicarEn:'2026-08-12T12:00:00Z'}))).toBe(false);expect(publica(base({caducarEn:'2026-08-10T12:00:00Z'}))).toBe(false)});
 it('rechaza color, enlace e imagen inválidos',()=>{const{service}=crearServicio();const valida=(x:PublicacionPublica)=>(service as unknown as {validar:(x:PublicacionPublica)=>PublicacionPublica}).validar(x);expect(()=>valida(base({color:'red'}))).toThrow(BadRequestException);expect(()=>valida(base({enlace:'javascript:alert(1)'}))).toThrow(BadRequestException);expect(()=>valida(base({imagen:'x'.repeat(2_800_001)}))).toThrow(BadRequestException)});
 it('crea una publicación sin reemplazar las demás',async()=>{const{service,repo}=crearServicio();repo.exist.mockResolvedValue(false);repo.findOne.mockResolvedValue(null);repo.save.mockImplementation(async x=>x);await expect(service.crear(base())).resolves.toMatchObject({id:'pub-1'});expect(repo.save).toHaveBeenCalledTimes(1);expect(repo.delete).not.toHaveBeenCalled()});
 it('protege identificadores inexistentes',async()=>{const{service,repo}=crearServicio();repo.exist.mockResolvedValue(false);repo.delete.mockResolvedValue({affected:0});await expect(service.actualizar('ausente',base())).rejects.toBeInstanceOf(NotFoundException);await expect(service.eliminar('ausente')).rejects.toBeInstanceOf(NotFoundException)});
});
>>>>>>> Stashed changes
