'use client';
import {useEffect,useMemo,useState} from 'react';
import {useConfirmacion} from '@/app/components/ConfirmProvider';
import {useEntradaConfirmada} from '@/app/components/InputProvider';
import {apiFetch} from '@/lib/api';
import {aplicarConfiguracion,ConfigDefinition} from '@/lib/configuracion';
interface Draft{id:string;numero:number;estado:string;values:Record<string,unknown>;motivo:string|null;creadoPor:string;creadoEn:string;baseVersion:number}
interface Version extends Draft{publicadoEn:string|null;publicadoPor:string|null}
export default function ConfiguracionGlobalPage(){
 const confirmar=useConfirmacion();
 const solicitarEntrada=useEntradaConfirmada();
 const[defs,setDefs]=useState<ConfigDefinition[]>([]),[draft,setDraft]=useState<Draft|null>(null),[values,setValues]=useState<Record<string,unknown>>({}),[published,setPublished]=useState<Record<string,unknown>>({}),[versions,setVersions]=useState<Version[]>([]),[search,setSearch]=useState(''),[category,setCategory]=useState('Todas'),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[warnings,setWarnings]=useState<any[]>([]),[preview,setPreview]=useState(false),[reason,setReason]=useState('');
 async function request(path:string,options?:RequestInit){const r=await apiFetch(path,options);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(Array.isArray(b.message)?b.message.join(', '):b.message||'Error de configuración');return b}
 async function load(){setError('');try{const[registry,pub,ver,d]=await Promise.all([request('/configuracion/admin/registro'),request('/configuracion/publica'),request('/configuracion/admin/versiones'),request('/configuracion/admin/borradores',{method:'POST'})]);setDefs(registry);const pv=Object.fromEntries(Object.entries(pub.values||{}).map(([k,v]:any)=>[k,v.value]));setPublished(pv);setVersions(ver);setDraft(d);setReason(d.motivo||'');setValues(Object.fromEntries(registry.filter((x:ConfigDefinition)=>x.nivel==='GLOBAL').map((x:ConfigDefinition)=>[x.key,d.values[x.key]??pv[x.key]??x.defaultValue])))}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(preview)aplicarConfiguracion({...published,...values});else aplicarConfiguracion(published)},[preview,values,published]);
 const globals=defs.filter(x=>x.nivel==='GLOBAL'),categories=['Todas',...Array.from(new Set(globals.map(x=>x.categoria)))];const shown=globals.filter(x=>(category==='Todas'||x.categoria===category)&&`${x.nombre} ${x.descripcion} ${x.key}`.toLowerCase().includes(search.toLowerCase()));const changed=useMemo(()=>Object.keys(values).filter(k=>JSON.stringify(values[k])!==JSON.stringify(published[k]??defs.find(d=>d.key===k)?.defaultValue)),[values,published,defs]);
 function change(key:string,value:unknown){setValues(x=>({...x,[key]:value}));setDirty(true);setMessage('')}
 async function save(){if(!draft)return;setBusy(true);setError('');try{const d=await request(`/configuracion/admin/borradores/${draft.id}`,{method:'PUT',body:JSON.stringify({values,motivo:reason||undefined})});setDraft(d);setDirty(false);setMessage('Borrador guardado. Los usuarios todavía no ven estos cambios.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function validate(){if(!draft)return;await save();try{const v=await request(`/configuracion/admin/borradores/${draft.id}/validar`,{method:'POST'});setWarnings(v.warnings||[]);setMessage(v.valid?'Validación completada. El borrador está listo para publicar.':'Hay errores de validación.')}catch(e:any){setError(e.message)}}
 async function publish(){if(!draft||!reason.trim()){setError('Indicá el motivo del cambio antes de publicar.');return}if(!await confirmar({titulo:'Publicar configuración',mensaje:`Se publicarán ${changed.length} cambios globales. ¿Continuar?`,confirmar:'Publicar',peligro:true}))return;setBusy(true);try{await save();await request(`/configuracion/admin/borradores/${draft.id}/publicar`,{method:'POST'});setPreview(false);setMessage('Configuración publicada correctamente.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function restore(v:Version){const motivo=await solicitarEntrada({titulo:'Restaurar configuración',mensaje:`Indique el motivo para restaurar la versión ${v.numero}.`,etiqueta:'Motivo',confirmar:'Continuar',requerida:true});if(!motivo)return;if(!await confirmar({titulo:'Restaurar configuración',mensaje:'Se creará una nueva versión publicada con esos valores. ¿Continuar?',confirmar:'Restaurar',peligro:true}))return;try{await request(`/configuracion/admin/versiones/${v.id}/restaurar`,{method:'POST',body:JSON.stringify({motivo})});setMessage(`Versión ${v.numero} restaurada como una nueva publicación.`);await load()}catch(e:any){setError(e.message)}}
 async function exportConfig(){try{const data=await request('/configuracion/admin/exportar');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`sigbo-config-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}catch(e:any){setError(e.message)}}
 if(error&&!draft)return <div className="service-validation"><strong>No se pudo abrir la configuración global</strong>{error}<p>La migración 021 y un permiso administrativo son obligatorios.</p></div>;
 return <div className={`config-admin${preview?' preview-active':''}`}><div className="config-admin-toolbar"><div><span className="topbar-eyebrow">Registro central</span><h2>Configuración global</h2><p>{draft?`Borrador v${draft.numero} · base publicada v${draft.baseVersion}`:'Cargando…'}</p></div><div className="service-actions"><button type="button" className="service-secondary" onClick={()=>setPreview(!preview)}>{preview?'Cerrar vista previa':'Vista previa'}</button><button type="button" className="service-secondary" onClick={save} disabled={!dirty||busy}>Guardar borrador</button><button type="button" className="service-secondary" onClick={validate} disabled={busy}>Validar</button><button type="button" className="btn-primary" onClick={publish} disabled={busy||!changed.length}>Publicar {changed.length?`(${changed.length})`:''}</button></div></div>{error&&<div className="service-validation" role="alert">{error}</div>}{message&&<div className="service-readonly" role="status">{message}</div>}{warnings.map((w,i)=><div className="service-validation" key={i}>{w.message}</div>)}
 <div className="config-admin-layout"><aside className="card"><input className="input-field" type="search" placeholder="Buscar configuración…" value={search} onChange={e=>setSearch(e.target.value)}/><nav>{categories.map(x=><button type="button" className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}<span>{x==='Todas'?globals.length:globals.filter(d=>d.categoria===x).length}</span></button>)}</nav><button type="button" className="service-secondary" onClick={exportConfig}>Exportar configuración</button></aside><main><section className="card config-change-reason"><label>Motivo de la publicación<textarea className="input-field" rows={2} value={reason} onChange={e=>{setReason(e.target.value);setDirty(true)}} placeholder="Explicá por qué se realiza este cambio"/></label></section><div className="config-definition-list">{shown.map(def=><AdminField key={def.key} def={def} value={values[def.key]??def.defaultValue} original={published[def.key]??def.defaultValue} onChange={v=>change(def.key,v)} onReset={()=>change(def.key,def.defaultValue)}/>)}</div></main></div>
 <section className="config-history"><div className="section-heading"><h2>Historial de versiones</h2><span>{versions.length} versiones</span></div>{versions.length?<div className="publication-list">{versions.map(v=><article className="card" key={v.id}><div><span className={`service-status ${v.estado==='PUBLICADO'?'status-finalizada':''}`}>{v.estado}</span><h3>Versión {v.numero}</h3><p>{v.motivo||'Sin motivo registrado'}</p><small>{new Date(v.creadoEn).toLocaleString('es-PY')}</small></div><div className="publication-actions">{v.estado!=='PUBLICADO'&&<button type="button" onClick={()=>restore(v)}>Restaurar</button>}</div></article>)}</div>:<div className="card public-empty">Aún no hay versiones publicadas.</div>}</section></div>
}
function AdminField({def,value,original,onChange,onReset}:{def:ConfigDefinition;value:unknown;original:unknown;onChange:(v:unknown)=>void;onReset:()=>void}){const modified=JSON.stringify(value)!==JSON.stringify(original);return <article className={`card config-definition${modified?' modified':''}`}><div className="config-definition-head"><div><span>{def.key}</span><h3>{def.nombre}</h3><p>{def.descripcion}</p></div><button type="button" onClick={onReset} disabled={JSON.stringify(value)===JSON.stringify(def.defaultValue)}>Restablecer</button></div><div className="config-control">{def.tipo==='booleano'?<label className="service-toggle"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>{value?'Activado':'Desactivado'}</label>:def.tipo==='color'?<><input type="color" value={String(value)} onChange={e=>onChange(e.target.value)}/><code>{String(value)}</code></>:def.tipo==='numero'?<input className="input-field" type="number" min={def.min} max={def.max} value={Number(value)} onChange={e=>onChange(Number(e.target.value))}/>:def.allowed?<select className="input-field" value={String(value)} onChange={e=>onChange(def.allowed?.find(x=>String(x)===e.target.value))}>{def.allowed.map(x=><option key={String(x)} value={String(x)}>{String(x)}</option>)}</select>:def.control==='textarea'?<textarea className="input-field" rows={3} value={String(value??'')} onChange={e=>onChange(e.target.value)}/>:<input className="input-field" value={String(value??'')} onChange={e=>onChange(e.target.value)}/>}</div><footer><span>Predeterminado: <code>{String(def.defaultValue)}</code></span><span>Origen actual: {modified?'Borrador':'Publicado/sistema'}</span><span>{def.realtime?'Tiempo real':def.reload?'Requiere recarga':''}</span></footer></article>}
