'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '@/lib/api';
import { SystemIcon } from '@/app/components/SystemIcon';

interface Comunicacion { id: string; tipo: string; estado: string; actualizadoEn: string; servicio?: { numeroServicio: string; fechaHoraAviso: string; direccion: string | null }; formulario: { denunciante?: string; direccion?: string }; }
export default function ServiciosPage() {
  const [items, setItems] = useState<Comunicacion[] | null>(null); const [error, setError] = useState('');
  useEffect(() => { apiFetch('/servicios/comunicaciones').then(async (res) => { if (!res.ok) throw new Error('No se pudieron cargar las comunicaciones'); setItems(await res.json()); }).catch((err) => setError(err.message)); }, []);
  return <div><section className="dashboard-hero" style={{ minHeight: 230 }}><div><div className="hero-kicker">Registro operativo</div><h2>Servicios en terreno,<br />datos bajo control.</h2><p>Comunicación completa, borradores recuperables, validación y seguimiento de cada intervención.</p></div><div className="hero-stamp"><div className="hero-time">{items?.length ?? '—'}</div><div className="hero-date">Comunicaciones registradas</div></div></section><div className="section-heading"><h2>Comunicaciones de servicio</h2><Link className="btn-primary" href="/dashboard/servicios/nuevo">+ Cargar nuevo servicio</Link></div>{error && <p className="form-error">{error}</p>}{items === null ? <p style={{ color: 'var(--muted)' }}>Cargando comunicaciones…</p> : items.length === 0 ? <section className="card" style={{ textAlign: 'center', padding: 42 }}><div className="module-icon" style={{ margin: '0 auto 13px' }}><SystemIcon name="document" size={20} /></div><h2 style={{ fontSize: 17 }}>Aún no hay comunicaciones</h2><p style={{ color: 'var(--muted)', margin: '7px 0 18px', fontSize: 13 }}>Registre la primera comunicación de servicio para comenzar.</p><Link className="btn-primary" href="/dashboard/servicios/nuevo">Cargar nuevo servicio</Link></section> : <div className="service-list-wrap"><table><thead><tr><th>Número</th><th>Tipo</th><th>Ubicación</th><th>Estado</th><th>Actualizado</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.servicio?.numeroServicio || 'Borrador'}</strong></td><td>{item.tipo === 'INCENDIO' ? 'Incendio' : 'Otras ocurrencias'}</td><td>{item.servicio?.direccion || item.formulario?.direccion || 'Sin ubicación'}</td><td><span className="badge">{item.estado.replace('_', ' ')}</span></td><td>{new Date(item.actualizadoEn).toLocaleString('es-PY')}</td><td><Link className="service-list-action" href={`/dashboard/servicios/nuevo?id=${encodeURIComponent(item.id)}`}>{item.estado === 'FINALIZADA' || item.estado === 'ANULADO' ? 'Ver' : 'Continuar'}</Link></td></tr>)}</tbody></table></div>}</div>;
}
