'use client';
import {useEffect,useMemo,useState} from 'react';
import {apiFetch} from '@/lib/api';
import {aplicarConfiguracion,ConfigDefinition,guardarPreferenciasDispositivo,preferenciasDispositivo} from '@/lib/configuracion';

export default function PreferenciasPage(){
 const[defs,setDefs]=useState<ConfigDefinition[]>([]),[values,setValues]=useState<Record<string,unknown>>({}),[message,setMessage]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([apiFetch('/configuracion/registro-preferencias'),apiFetch('/configuracion/mis-preferencias')]).then(async([rr,rp])=>{if(!rr.ok||!rp.ok)throw new Error('No se pudieron cargar las preferencias');const registry:ConfigDefinition[]=await rr.json(),prefs=await rp.json();const effective=Object.fromEntries(Object.entries(prefs.effective||{}).map(([k,v]:any)=>[k,v.value]));setDefs(registry);setValues({...effective,...prefs.values,...preferenciasDispositivo()})}).catch(e=>setError(e.message))},[]);
 const groups=useMemo(()=>Object.entries(defs.reduce((a:Record<string,ConfigDefinition[]>,d)=>{(a[d.categoria]??=[]).push(d);return a},{})),[defs]);
 function change(key:string,value:unknown){const next={...values,[key]:value};setValues(next);aplicarConfiguracion(next)}
 async function save(){setSaving(true);setError('');const allowed=Object.fromEntries(defs.map(d=>[d.key,values[d.key]??d.defaultValue]));try{const r=await apiFetch('/configuracion/mis-preferencias',{method:'PUT',body:JSON.stringify({values:allowed})});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.message||'No se pudieron guardar las preferencias')}guardarPreferenciasDispositivo(allowed);setMessage('Preferencias sincronizadas con tu cuenta y este dispositivo.')}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 return <div className="profile-settings"><div className="service-heading"><div><span className="topbar-eyebrow">Mi cuenta</span><h2>Preferencias</h2><p>Estas opciones se sincronizan con tu usuario y no modifican la configuración institucional.</p></div></div>{error&&<div className="service-validation">{error}</div>}{message&&<div className="service-readonly">{message}</div>}{groups.map(([name,list])=><section className="card" key={name}><h3>{name}</h3>{list.map(d=><Preference key={d.key} def={d} value={values[d.key]??d.defaultValue} change={v=>change(d.key,v)}/>)}</section>)}<button type="button" className="btn-primary" onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar y sincronizar'}</button></div>
}
function Preference({def,value,change}:{def:ConfigDefinition;value:unknown;change:(v:unknown)=>void}){return <label className="config-field"><span><b>{def.nombre}</b><small>{def.descripcion}</small></span>{def.tipo==='booleano'?<input type="checkbox" checked={!!value} onChange={e=>change(e.target.checked)}/>:def.tipo==='color'?<input type="color" value={String(value)} onChange={e=>change(e.target.value)}/>:def.control==='slider'?<span className="config-slider"><input type="range" min={def.min} max={def.max} value={Number(value)} onChange={e=>change(Number(e.target.value))}/><output>{String(value)}{def.unidad}</output></span>:def.allowed?<select value={String(value)} onChange={e=>change(def.allowed?.find(x=>String(x)===e.target.value))}>{def.allowed.map(x=><option key={String(x)}>{String(x)}</option>)}</select>:<input value={String(value??'')} onChange={e=>change(e.target.value)}/>}</label>}
