export type ConfigTipo = 'texto' | 'numero' | 'booleano' | 'selector' | 'color';
export type ConfigNivel = 'VISITANTE' | 'USUARIO' | 'GLOBAL';

export interface ConfigDefinition {
  key: string; nombre: string; descripcion: string; categoria: string; nivel: ConfigNivel;
  tipo: ConfigTipo; control: string; defaultValue: unknown; allowed?: unknown[];
  min?: number; max?: number; unidad?: string; public: boolean; userOverride: boolean;
  permission?: string; realtime: boolean; reload: boolean; sensitive: boolean; version: string;
}

const d = (value: ConfigDefinition) => value;
export const CONFIG_REGISTRY: ConfigDefinition[] = [
  d({key:'appearance.theme',nombre:'Tema',descripcion:'Tema visual preferido.',categoria:'Apariencia',nivel:'VISITANTE',tipo:'selector',control:'radio',defaultValue:'auto',allowed:['light','dark','auto'],public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'appearance.accent',nombre:'Color de acento',descripcion:'Color institucional para acciones destacadas.',categoria:'Apariencia',nivel:'VISITANTE',tipo:'color',control:'color',defaultValue:'#2563eb',public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'appearance.fontSize',nombre:'Tamaño de fuente',descripcion:'Escala base de lectura.',categoria:'Apariencia',nivel:'VISITANTE',tipo:'numero',control:'slider',defaultValue:100,min:80,max:140,unidad:'%',public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'appearance.density',nombre:'Densidad',descripcion:'Espaciado general de la interfaz.',categoria:'Apariencia',nivel:'VISITANTE',tipo:'selector',control:'select',defaultValue:'comfortable',allowed:['compact','comfortable','spacious'],public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'appearance.radius',nombre:'Radio visual',descripcion:'Redondez de controles y tarjetas.',categoria:'Apariencia',nivel:'VISITANTE',tipo:'numero',control:'slider',defaultValue:8,min:0,max:24,unidad:'px',public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'accessibility.highContrast',nombre:'Contraste alto',descripcion:'Aumenta contraste de textos y bordes.',categoria:'Accesibilidad',nivel:'VISITANTE',tipo:'booleano',control:'switch',defaultValue:false,public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'accessibility.reducedMotion',nombre:'Reducir animaciones',descripcion:'Reduce movimiento no esencial.',categoria:'Accesibilidad',nivel:'VISITANTE',tipo:'booleano',control:'switch',defaultValue:false,public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'accessibility.underlineLinks',nombre:'Subrayar enlaces',descripcion:'Hace más reconocibles los enlaces.',categoria:'Accesibilidad',nivel:'VISITANTE',tipo:'booleano',control:'switch',defaultValue:false,public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'accessibility.readableFont',nombre:'Fuente legible',descripcion:'Prioriza una fuente de alta legibilidad.',categoria:'Accesibilidad',nivel:'VISITANTE',tipo:'booleano',control:'switch',defaultValue:false,public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'region.language',nombre:'Idioma',descripcion:'Idioma preferido.',categoria:'Idioma y región',nivel:'USUARIO',tipo:'selector',control:'language',defaultValue:'es-PY',allowed:['es-PY'],public:true,userOverride:true,realtime:false,reload:true,sensitive:false,version:'1.0'}),
  d({key:'region.timezone',nombre:'Zona horaria',descripcion:'Zona horaria de presentación.',categoria:'Idioma y región',nivel:'USUARIO',tipo:'selector',control:'timezone',defaultValue:'America/Asuncion',allowed:['America/Asuncion','UTC'],public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'behavior.pageSize',nombre:'Resultados por página',descripcion:'Cantidad predeterminada de filas.',categoria:'Comportamiento',nivel:'USUARIO',tipo:'selector',control:'select',defaultValue:25,allowed:[10,25,50,100],public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'behavior.confirmDangerous',nombre:'Confirmar acciones importantes',descripcion:'Solicita confirmación antes de acciones sensibles.',categoria:'Comportamiento',nivel:'USUARIO',tipo:'booleano',control:'switch',defaultValue:true,public:true,userOverride:true,realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'identity.appName',nombre:'Nombre de la aplicación',descripcion:'Identidad pública de la plataforma.',categoria:'Identidad',nivel:'GLOBAL',tipo:'texto',control:'text',defaultValue:'SIGBO-CBVC',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'identity.tagline',nombre:'Eslogan',descripcion:'Eslogan institucional.',categoria:'Identidad',nivel:'GLOBAL',tipo:'texto',control:'textarea',defaultValue:'Sistema integral de gestión',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'tokens.primary',nombre:'Color primario',descripcion:'Color principal del sistema.',categoria:'Tokens de diseño',nivel:'GLOBAL',tipo:'color',control:'color',defaultValue:'#0f3b70',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'tokens.accent',nombre:'Color de acento global',descripcion:'Color para acciones destacadas.',categoria:'Tokens de diseño',nivel:'GLOBAL',tipo:'color',control:'color',defaultValue:'#2563eb',public:true,userOverride:true,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'tokens.background',nombre:'Fondo claro',descripcion:'Fondo principal del tema claro.',categoria:'Tokens de diseño',nivel:'GLOBAL',tipo:'color',control:'color',defaultValue:'#f3f7f8',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'tokens.text',nombre:'Texto principal',descripcion:'Texto principal del tema claro.',categoria:'Tokens de diseño',nivel:'GLOBAL',tipo:'color',control:'color',defaultValue:'#10263f',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'tokens.surface',nombre:'Superficie',descripcion:'Fondo de tarjetas y controles.',categoria:'Tokens de diseño',nivel:'GLOBAL',tipo:'color',control:'color',defaultValue:'#ffffff',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'tokens.danger',nombre:'Error',descripcion:'Color semántico de error.',categoria:'Tokens de diseño',nivel:'GLOBAL',tipo:'color',control:'color',defaultValue:'#bd3d39',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'navigation.defaultPage',nombre:'Página inicial',descripcion:'Ruta inicial después del acceso.',categoria:'Navegación',nivel:'GLOBAL',tipo:'selector',control:'page',defaultValue:'/dashboard',allowed:['/dashboard','/dashboard/servicios','/dashboard/asistencia'],public:false,userOverride:false,permission:'configuracion:editar_borrador',realtime:false,reload:true,sensitive:false,version:'1.0'}),
  d({key:'operations.sessionMinutes',nombre:'Duración de sesión',descripcion:'Duración máxima de sesión autenticada.',categoria:'Seguridad global',nivel:'GLOBAL',tipo:'numero',control:'number',defaultValue:480,min:15,max:1440,unidad:'min',public:false,userOverride:false,permission:'configuracion:editar_borrador',realtime:false,reload:true,sensitive:false,version:'1.0'}),
  d({key:'maintenance.enabled',nombre:'Modo mantenimiento',descripcion:'Activa la pantalla de mantenimiento.',categoria:'Mantenimiento',nivel:'GLOBAL',tipo:'booleano',control:'switch',defaultValue:false,public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'maintenance.title',nombre:'Título de mantenimiento',descripcion:'Título público durante mantenimiento.',categoria:'Mantenimiento',nivel:'GLOBAL',tipo:'texto',control:'text',defaultValue:'Mantenimiento programado',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
  d({key:'maintenance.message',nombre:'Mensaje de mantenimiento',descripcion:'Información pública durante mantenimiento.',categoria:'Mantenimiento',nivel:'GLOBAL',tipo:'texto',control:'textarea',defaultValue:'Volveremos a estar disponibles pronto.',public:true,userOverride:false,permission:'configuracion:editar_borrador',realtime:true,reload:false,sensitive:false,version:'1.0'}),
];

export const CONFIG_BY_KEY = new Map(CONFIG_REGISTRY.map(x => [x.key, x]));
