'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api';
import { Cargando } from '@/app/components/Cargando';

type Detalle = { id: string; codigo: string; estado: string; nombreDenunciante: string; telefono: string; categoria: string; asuntoOtro: string | null; descripcion: string | null; creadoEn: string; servicio: { numero: string; fechaHora: string; direccion: string } | null; vehiculo: { nombre: string } | null; asignado: { username: string } | null; historial: { id: string; estadoAnterior: string | null; estadoNuevo: string; comentario: string | null; fecha: string }[]; evidencias: { id: string; tipo: string; nombre: string; mimeType: string; tamanoBytes: number }[]; tecnico?: { ip: string | null; userAgent: string | null; latitud: number | null; longitud: number | null; precisionUbicacion: number | null } };
const opciones = ['EN_REVISION', 'ASIGNADA', 'EN_INVESTIGACION', 'RESUELTA', 'CERRADA', 'DESCARTADA', 'DUPLICADA'];

export default function DetalleDenunciaPage({ params }: { params: { id: string } }) {
  const [item, setItem] = useState<Detalle | null>(null); const [estado, setEstado] = useState(''); const [comentario, setComentario] = useState(''); const [asignadoA, setAsignadoA] = useState(''); const [asignables, setAsignables] = useState<{ id: string; username: string }[]>([]); const [error, setError] = useState(''); const [cargando, setCargando] = useState(true); const [audioUrl, setAudioUrl] = useState<Record<string, string>>({});
  async function cargar() { setCargando(true); try { const r = await apiFetch(`/denuncias/${params.id}`); if (!r.ok) throw new Error('No pudimos cargar la denuncia.'); setItem(await r.json()); } catch (e) { setError(e instanceof Error ? e.message : 'No pudimos cargar la denuncia.'); } finally { setCargando(false); } }
  useEffect(() => { cargar(); apiFetch('/denuncias/asignables').then((r) => r.ok ? r.json() : []).then(setAsignables).catch(() => undefined); return () => Object.values(audioUrl).forEach(URL.revokeObjectURL); }, [params.id]);
  async function cambiarEstado() { if (!estado) return; setError(''); const r = await apiFetch(`/denuncias/${params.id}/estado`, { method: 'PATCH', body: JSON.stringify({ estado, comentario }) }); if (!r.ok) { const b = await r.json().catch(() => ({})); setError(b.message ?? 'No pudimos actualizar la denuncia.'); return; } setEstado(''); setComentario(''); cargar(); }
  async function asignar() { if (!asignadoA) return; setError(''); const r = await apiFetch(`/denuncias/${params.id}/asignar`, { method: 'POST', body: JSON.stringify({ usuarioId: asignadoA, comentario }) }); if (!r.ok) { const b = await r.json().catch(() => ({})); setError(b.message ?? 'No pudimos asignar la denuncia.'); return; } setAsignadoA(''); cargar(); }
  async function cargarAudio(evidencia: Detalle['evidencias'][number]) { const r = await apiFetch(`/denuncias/${params.id}/archivos/${evidencia.id}`); if (!r.ok) { setError('No pudimos abrir la evidencia.'); return; } const url = URL.createObjectURL(await r.blob()); if (!evidencia.mimeType.startsWith('audio/')) { window.open(url, '_blank', 'noopener,noreferrer'); return; } setAudioUrl((actual) => ({ ...actual, [evidencia.id]: url })); }
  if (cargando) return <Cargando texto="Cargando denuncia…" />;
  if (!item) return <p className="form-error">{error || 'No encontramos la denuncia.'}</p>;
  return <div className="denuncia-interna">
    <Link className="denuncia-back" href="/dashboard/denuncias">← Volver a denuncias</Link>
    <div className="section-heading"><div><p className="hero-kicker">{item.codigo}</p><h2>{item.categoria}</h2></div><span className="badge">{item.estado.replaceAll('_', ' ')}</span></div>
    {error && <p className="form-error" role="alert">{error}</p>}
    <div className="denuncia-detail-grid">
      <section className="card"><h3>Información recibida</h3><dl><dt>Denunciante</dt><dd>{item.nombreDenunciante}</dd><dt>Celular</dt><dd>{item.telefono}</dd><dt>Fecha</dt><dd>{new Date(item.creadoEn).toLocaleString('es-PY')}</dd>{item.asuntoOtro && <><dt>Sobre qué es</dt><dd>{item.asuntoOtro}</dd></>}</dl><h3>Descripción</h3><p>{item.descripcion || 'La explicación fue enviada mediante audio.'}</p>{item.servicio && <><h3>Servicio relacionado</h3><p><strong>{item.servicio.numero}</strong><br/>{new Date(item.servicio.fechaHora).toLocaleString('es-PY')}<br/>{item.servicio.direccion}</p></>}{item.vehiculo && <><h3>Móvil relacionado</h3><p>{item.vehiculo.nombre}</p></>}</section>
      <section className="card"><h3>Gestión</h3><p>Responsable: {item.asignado?.username ?? 'Sin asignar'}</p>{asignables.length > 0 && <div className="assignment-row"><select className="input-field" aria-label="Asignar responsable" value={asignadoA} onChange={(e) => setAsignadoA(e.target.value)}><option value="">Asignar responsable</option>{asignables.map((usuario) => <option key={usuario.id} value={usuario.id}>{usuario.username}</option>)}</select><button type="button" className="service-secondary" onClick={asignar} disabled={!asignadoA}>Asignar</button></div>}<label>Nuevo estado<select className="input-field" value={estado} onChange={(e) => setEstado(e.target.value)}><option value="">Seleccionar</option>{opciones.map((opcion) => <option key={opcion} value={opcion}>{opcion.replaceAll('_', ' ')}</option>)}</select></label><label>Comentario<textarea className="input-field" rows={3} value={comentario} onChange={(e) => setComentario(e.target.value)} /></label><button type="button" className="btn-primary" onClick={cambiarEstado} disabled={!estado}>Actualizar estado</button><h3>Evidencias</h3>{item.evidencias.length === 0 ? <p>Sin evidencias adjuntas.</p> : item.evidencias.map((evidencia) => <div className="evidencia-item" key={evidencia.id}><span>{evidencia.tipo === 'AUDIO' ? 'Audio' : 'Archivo'} · {evidencia.nombre}</span>{evidencia.mimeType.startsWith('audio/') ? (audioUrl[evidencia.id] ? <audio controls src={audioUrl[evidencia.id]}/> : <button type="button" className="service-secondary" onClick={() => cargarAudio(evidencia)}>Escuchar audio</button>) : <button type="button" className="service-secondary" onClick={() => cargarAudio(evidencia)}>Abrir evidencia</button>}</div>)}</section>
    </div>
    {item.tecnico && <section className="card technical-data"><h3>Datos técnicos restringidos</h3><p>IP: {item.tecnico.ip ?? 'No disponible'}</p><p>Ubicación: {item.tecnico.latitud !== null ? `${item.tecnico.latitud}, ${item.tecnico.longitud} · precisión ${item.tecnico.precisionUbicacion ?? '—'} m` : 'No compartida'}</p></section>}
    <section className="card"><h3>Historial</h3><ol className="denuncia-history">{item.historial.map((evento) => <li key={evento.id}><strong>{new Date(evento.fecha).toLocaleString('es-PY')} · {evento.estadoNuevo.replaceAll('_', ' ')}</strong>{evento.comentario && <span>{evento.comentario}</span>}</li>)}</ol></section>
  </div>;
}
