import { apiFetch } from './api';

export interface ConfigDefinition { key:string;nombre:string;descripcion:string;categoria:string;nivel:string;tipo:string;control:string;defaultValue:unknown;allowed?:unknown[];min?:number;max?:number;unidad?:string;public:boolean;userOverride:boolean;realtime:boolean;reload:boolean; }
export interface ResolvedValue {value:unknown;source:'SYSTEM'|'GLOBAL'|'USER'|'DEVICE'|'PREVIEW';overridable:boolean}
export const DEVICE_CONFIG_KEY='sigbo_device_preferences_v1';

export function preferenciasDispositivo():Record<string,unknown>{if(typeof window==='undefined')return{};try{return JSON.parse(localStorage.getItem(DEVICE_CONFIG_KEY)||'{}')}catch{return{}}}
export function guardarPreferenciasDispositivo(values:Record<string,unknown>){localStorage.setItem(DEVICE_CONFIG_KEY,JSON.stringify(values));aplicarConfiguracion(values);window.dispatchEvent(new CustomEvent('sigbo-config-change',{detail:values}));}
export function aplicarConfiguracion(values:Record<string,unknown>){if(typeof document==='undefined')return;const root=document.documentElement;const theme=String(values['appearance.theme']??'auto');root.dataset.theme=theme;root.dataset.density=String(values['appearance.density']??'comfortable');root.classList.toggle('config-high-contrast',!!values['accessibility.highContrast']);root.classList.toggle('config-reduced-motion',!!values['accessibility.reducedMotion']);root.classList.toggle('config-underline-links',!!values['accessibility.underlineLinks']);root.classList.toggle('config-readable-font',!!values['accessibility.readableFont']);root.style.setProperty('--config-font-scale',`${Number(values['appearance.fontSize']??100)/100}`);root.style.setProperty('--config-radius',`${Number(values['appearance.radius']??8)}px`);const accent=String(values['appearance.accent']??values['tokens.accent']??'#2563eb');if(/^#[0-9a-f]{6}$/i.test(accent))root.style.setProperty('--signal',accent);for(const [k,css] of Object.entries({'tokens.primary':'--ink','tokens.background':'--paper','tokens.text':'--config-text','tokens.surface':'--surface','tokens.danger':'--danger'}))if(typeof values[k]==='string')root.style.setProperty(css,String(values[k]));}
export async function cargarPublica(){const r=await apiFetch('/configuracion/publica',{cache:'no-store'});if(!r.ok)throw new Error('No se pudo cargar la configuración pública');return r.json();}
export async function cargarRegistroPublico():Promise<ConfigDefinition[]>{const r=await apiFetch('/configuracion/registro-publico');if(!r.ok)throw new Error('No se pudo cargar el registro');return r.json();}
